mysite/cmu/urls.py
from django.urls import path

from . import views

app_name = 'cmu'

urlpatterns = [
    path('', views.main, name='main'), 
    path('main-page/', views.index, name='index')
]

mysite/games/urls.py
from django.urls import path

from . import views

app_name = 'games'

urlpatterns = [
    path('', views.main, name='main'), 
    path("main/<int:page>", views.main, name = "main_paginate"),
    path('my-games/', views.my_games, name='my_games'), 
    path("my-games/<int:page>", views.my_games, name = "my_games_paginate"), 
    path("<str:game_name>/", views.game_detail, name="game_detail"),
    path("my-games/<str:game_name>/", views.my_game_detail, name="game_detail"), 
    path('<str:game_name>/buy/', views.buy_game, name='buy_game'), 
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmu.urls')),  
    path('users/', include('users.urls')), 
    path('games/', include('games.urls')) 
]

mysite/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'), 
    path('login/', views.login_user, name='login'), 
    path('logout/', views.logout_user, name='logout'), 
    path('create-profile/', views.create_profile, name='create_profile'),  
]

mysite/cmu/models.py
from django.db import models

# Create your models here.

mysite/games/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class Genre(models.Model):
    name = models.CharField(max_length=20, null=False, unique=True)

    def __str__(self):
        return self.name

class Game(models.Model):
    genre = models.ManyToManyField(Genre)
    name = models.CharField(max_length=25, null=False, unique=True)
    title = CloudinaryField('image')
    price = models.PositiveIntegerField(null=True)
    date_of_release = models.DateField(null=True)

    def __str__(self):
        return self.name

mysite/users/models.py
from django.contrib.auth.models import User
from django.db import models

from cloudinary.models import CloudinaryField

from games.models import Game


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = CloudinaryField('image')
    birthday = models.DateField(null=False)
    country = models.CharField(max_length=10, null=False)
    email = models.EmailField(null=False)
    is_banned = models.BooleanField(default=False)
    game = models.ManyToManyField(Game, blank=True)

    def __str__(self):
        return self.user.username

mysite/users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile



class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=25, required=True, widget=forms.TextInput())
    email = forms.CharField(max_length=50, required=True, widget=forms.TextInput())
    password1 = forms.CharField(max_length=25, required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=25, required=True, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password1"]


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())
    birthday = forms.DateField(widget=forms.DateInput)
    country = forms.CharField(max_length=10, required=True, widget=forms.TextInput())
    email = forms.EmailField(max_length=50, required=True, widget=forms.EmailInput())

    class Meta:
        model = Profile
        fields = ['avatar', 'birthday', 'country', 'email']

mysite/cmu/views.py
from django.shortcuts import render
from django.http import HttpResponse

from datetime import datetime

from users.models import Profile

def main(request):
    return render(request, 'cmu/main.html')


def index(request):
    #profile = Profile.objects.all()
    profile = Profile.objects.get(user=request.user)
    age = (datetime.now().date() - profile.birthday).days // 365
    profile = {'profile': profile, 'age': age}
    return render(request, 'cmu/index.html', profile)

mysite/games/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Game, Genre

@login_required
def main(request, page=1):
    games = Game.objects.all()
    genres = Genre.objects.all()
    per_page = 6
    paginator = Paginator(list(games), per_page)
    games_on_page = paginator.page(page)
    return render(request, 'games/games.html', context={'games':games_on_page, 'genres': genres})

@login_required
def my_games(request, page=1):
    if request.user.is_authenticated:
        user_games = request.user.profile.game.all()
    else:
        user_games = None
    
    games = Game.objects.all()
    genres = Genre.objects.all()
    per_page = 6
    paginator = Paginator(list(games), per_page)
    games_on_page = paginator.page(page)
    
    return render(request, 'games/my_games.html', context={'games': games_on_page, 'genres': genres, 'user_games': user_games})


@login_required
def game_detail(request, game_name):
    game = get_object_or_404(Game, name=game_name)
    user = request.user
    is_purchased = user.profile.game.filter(name=game_name).exists()
    return render(request, 'games/game_detail.html', {'game_detail': game, 'is_purchased': is_purchased})


@login_required
def my_game_detail(request, game_name):
    game = get_object_or_404(Game, name=game_name)
    return render(request, 'games/my_game_detail.html', {'game_detail': game})


@login_required
def buy_game(request, game_name):
    game = get_object_or_404(Game, name=game_name)
    if request.user.profile.game.filter(name=game_name).exists():
        messages.error(request, 'You already own this game.')
    else:
        request.user.profile.game.add(game)
        messages.success(request, f'You have successfully bought {game_name}.')
    return redirect('games:game_detail', game_name=game_name)

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import RegisterForm, LoginForm, ProfileForm


def signup_user(request):
    if request.user.is_authenticated:
        return redirect(to='cmu:index')
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(to='users:create_profile')
        
        else:
            return render(request, 'users/signup.html', context={'form': form})
    return render(request, 'users/signup.html', context={"form": RegisterForm()})


@login_required
def create_profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect(to='cmu:index')

    else:
        profile_form = ProfileForm()

    return render(request, 'users/create_profile.html', {'profile_form': profile_form})

def login_user(request):
    if request.user.is_authenticated:
        return redirect(to='cmu:index')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='cmu:index')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logout_user(request):
    logout(request)
    return redirect(to='cmu:main')

mysite/cmu/templates/cmu/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CMU</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'cmu/styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'cmu/favicon.png' %}"/>
</head>
<body>
    {% block content %}
    {% endblock %}
    <script src="{% static 'cmu/script.js' %}"></script>
</body>
</html>

mysite/cmu/templates/cmu/base2.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CMU</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'cmu/main_page.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'cmu/favicon.png' %}">
    <style>
        .header-image {
            width: 100%;
            max-height: 100px; /* Или любое другое значение, которое определяет максимальную высоту */
            object-fit: cover; /* Сохранять соотношение сторон и подгонять изображение по размеру контейнера */
        }
        header {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <header class="mb-3">
        <a href="{% url 'cmu:index' %}">
            <img class="header-image" src="{% static 'cmu/head.jpeg' %}" alt="Header Image">
        </a>
    </header>
    <div class="position-absolute top-0 end-0 m-4">
        <a href="{% url 'users:logout' %}">
            <button type="button" class="btn btn-primary">Logout</button>
        </a>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3" style=" border: 1px solid rgb(255, 0, 0); border-radius: 20px;">
                {% block left_content %}
                {% endblock %}
            </div>

            <div class="col-md-6">
                {% block center_content %}
                {% endblock %}
            </div>

            <div class="col-md-3" style=" border: 1px solid rgb(255, 0, 0); border-radius: 20px;">
                {% block right_content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

mysite/cmu/templates/cmu/index.html
{% extends "cmu/base2.html" %}

{% block center_content %}
<!-- Центральный блок -->
<div class="container d-flex flex-column" style="height: calc(100vh - 100px); border: 1px solid rgb(255, 0, 0);  border-radius: 20px;">
    <div class="row justify-content-center flex-grow-1">
        <div class="col-md-12 text-center">
            {% if user.is_authenticated %}
                <div class="mb-3">
                    <img class="avatar" src="{{ profile.avatar.url }}" alt="photo">
                    <h1>{{ user.username }}</h1>
                    <h1>{{ age }}</h1>
                    <h1>{{ profile.country }}</h1>
                    <h1>{{ profile.email }}</h1>
                    <ul class="list-group list-group-horizontal.flex-fill">
                        <li class="list-group-item"><a href="{% url 'games:my_games' %}">My games</a></li>
                        <li class="list-group-item">{{ profile.game.count }}</li>
                    </ul>
                    <ul class="list-group list-group-horizontal-sm.flex-fill">
                        <li class="list-group-item">My songs</li>
                        <li class="list-group-item">{{ profile.song.count }}</li>
                    </ul>
                    <ul class="list-group list-group-horizontal-lg.flex-fill">
                        <li class="list-group-item">My films</li>
                        <li class="list-group-item">{{ profile.film.count }}</li>
                    </ul>
                    
                </div>
            {% endif %}
        </div>
    </div>
    <!-- Добавлен блок с четырьмя кнопками -->
    <div class="row justify-content-between">
        <div class="col-md-2">
            <a href="{% url 'games:main' %}" class="btn btn-primary">Games</a>
        </div>
        <div class="col-md-2">
            <button type="button" class="btn btn-primary">Button 2</button>
        </div>
        <div class="col-md-2">
            <button type="button" class="btn btn-primary">Button 3</button>
        </div>
        <div class="col-md-2">
            <button type="button" class="btn btn-primary">Button 4</button>
        </div>
    </div>
</div>
{% endblock %}

mysite/cmu/templates/cmu/main.html
{% extends "cmu/base.html"%}

{% block content %}
<div class="text-container">
    <h1>Добро пожаловать в CMU</h1>
    <p class="hidden">Ваш персональный путеводитель в уникальную метавселенную развлечений! Здесь ваши любимые игры, музыка, фильмы и сериалы соединяются воедино, создавая неповторимый опыт развлечений.</p>
    <p class="hidden">Откройте для себя грани виртуальных миров, наслаждайтесь увлекательными игровыми приключениями, открывайте новые музыкальные треки, окунитесь в захватывающие сюжеты фильмов и сериалов. CMU — это не просто платформа, это общество единомышленников, где можно делиться впечатлениями, обсуждать фаворитов и находить новых друзей, разделяющих ваши интересы.</p>
    <p class="hidden">Присоединяйтесь к нам и откройте для себя новый уровень развлечений, где ваш виртуальный опыт становится реальностью. В CMU мы не просто предлагаем контент, мы предлагаем погрузиться в невероятное приключение, созданное специально для вас. Добро пожаловать в мир, где развлечения становятся персональными!</p>
    <p class="hidden">Создайте свой уникальный профиль, подключайтесь к сообществам по интересам, и вместе с CMU погрузитесь в мир удовольствия и развлечений. Добро пожаловать в будущее развлечений — добро пожаловать в CMU!</p>

</div>
    <div class="btn-container">
        <a href="{% url 'users:signup' %}">
            <button type="button" class="btn btn-outline-primary btn-lg">SignUp</button>
        </a>
        <a href="{% url 'users:login' %}">
            <button type="button" class="btn btn-outline-primary btn-lg">Login</button>
        </a>
    </div>

{% endblock %}

mysite/games/templates/games/game_detail.html
{% extends 'cmu/base2.html' %}
{% block center_content %}

{% if game_detail %}
<div class="container">
    <img src="{{ game_detail.title.url }}" alt="title">
    <h3>{{ game_detail.name }}</h3>
    <p><strong>Price:</strong> {{ game_detail.price }} $</p>
    <p><strong>Date of release:</strong> {{ game_detail.date_of_release }} $</p>
    {% if user.is_authenticated %}
        {% if is_purchased %}
            <p>Куплено</p>
        {% else %}
            <form action="{% url 'games:buy_game' game_detail.name %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Купить</button>
            </form>
        {% endif %}
    {% else %}
        <p>Пожалуйста, <a href="{% url 'login' %}">войдите</a>, чтобы купить эту игру.</p>
    {% endif %}
</div>
{% endif %}

{% endblock %}

mysite/games/templates/games/games.html
{% extends "cmu/base2.html" %}

{% block center_content %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for game in games %}
        <div class="col mb-4">
            <div class="card" style="border-radius: 20px; height: 100%;">
                
                    <img src="{{ game.title.url }}" class="card-img-top" alt="Game Image" style="height: 200px; object-fit: cover;">
                
                <div class="card-body">
                    <a href="/games/{{game.name}}">
                        <h5 class="card-title">{{ game.name }}</h5>
                    </a>
                    <p class="card-text">Price: {{ game.price }}</p>
                    <p class="card-text">Realise: {{ game.date_of_release }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if games.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'games:main_paginate' games.previous_page_number %}">Previous</a></li>
        {% endif %}
        {% if games.has_next %}
        <li class="page-item"><a class="page-link" href="{% url 'games:main_paginate' games.next_page_number %}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

mysite/games/templates/games/my_game_detail.html
{% extends 'cmu/base2.html' %}
{% block center_content %}

{% if game_detail %}
<div class="container">
    <img src="{{ game_detail.title.url }}" alt="title">
    <h3>{{ game_detail.name }}</h3>
    <p><strong>Price:</strong> {{ game_detail.price }} $</p>
    <p><strong>Date of release:</strong> {{ game_detail.date_of_release }}</p>
</div>
{% endif %}

{% endblock %}

mysite/games/templates/games/my_games.html
{% extends "cmu/base2.html" %}

{% block center_content %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for game in user_games %}
        <div class="col mb-4">
            <div class="card" style="border-radius: 20px; height: 100%;">
                <img src="{{ game.title.url }}" class="card-img-top" alt="Game Image" style="height: 200px; object-fit: cover;">
                <div class="card-body">
                    <a href="{% url 'games:game_detail' game.name %}">
                        <h5 class="card-title">{{ game.name }}</h5>
                    </a>
                    <p class="card-text">Price: {{ game.price }}</p>
                    <p class="card-text">Realise: {{ game.date_of_release }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if games.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'games:my_games_paginate' games.previous_page_number %}">Previous</a></li>
        {% endif %}
        {% if games.has_next %}
        <li class="page-item"><a class="page-link" href="{% url 'games:my_games_paginate' games.next_page_number %}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

mysite/users/templates/users/create_profile.html
{% extends "cmu/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:create_profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>Create Your Profile</h2>
    <div class="mb-3">
        <label for="id_avatar" class="form-label">Avatar</label>
        {{ profile_form.avatar }}
    </div>
    <div class="mb-3">
        <label for="id_birthday" class="form-label">Birthday</label>
        {{ profile_form.birthday }}
    </div>
    <div class="mb-3">
        <label for="id_country" class="form-label">Country</label>
        {{ profile_form.country }}
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email</label>
        {{ profile_form.email }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

mysite/users/templates/users/login.html
{% extends "cmu/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div class="row g-3 align-items-center">
        <div class="col">
            <label for="inputUsername" class="col-form-label">Username</label>
        </div>
        <div class="col">
            <input type="text" id="inputUsername" class="form-control" name="username">
        </div>
    </div>

    <div class="row g-3 align-items-center mt-2">
        <div class="col">
            <label for="inputPassword" class="col-form-label">Password</label>
        </div>
        <div class="col">
            <input type="password" id="inputPassword" class="form-control" name="password" aria-describedby="passwordHelpInline">
        </div>
    </div>

    <div class="grid">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

{% endblock %}

mysite/users/templates/users/signup.html
{% extends "cmu/base.html" %}

{% block content %}

    <div>
        <h2>Sign Up</h2>
    </div>

    <form method="post" action="{% url 'users:signup' %}">
        {% csrf_token %}
        <div>
            <label> Username:
                {{ form.username }}
            </label>
            <span>{{ form.errors.username }}</span>
        </div>
        <div>
            <label> Email:
                {{ form.email }}
            </label>
            <span>{{ form.errors.email }}</span>
        </div>
        <div>
            <label> Password:
                {{ form.password1 }}
            </label>
            <span>{{ form.errors.password1 }}</span>
        </div>
        <div>
            <label> Password confirmation:
                {{ form.password2 }}
            </label>
            <span>{{ form.errors.password2 }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>

{% endblock %}